project:
  type: website
  output-dir: docs

website:
  title: "Joshua Rigsby - MUSA 5080 Portfolio"
  navbar:
     left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1 Notes
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2 Notes
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3 Notes
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4 Notes
          - href: weekly-notes/week-05-notes.qmd
            text: Week 5 Notes
          - href: weekly-notes/week-06-notes.qmd
            text: Week 6 Notes
          - href: weekly-notes/week-07-notes.qmd
            text: Week 7 Notes
          - href: weekly-notes/week-08-notes.qmd
            text: Week 8 Notes
            
      - text: Labs
        menu:
          - href: labs/lab0/lab0_template.qmd
            text: Lab 0
      - text: Assignments
        menu:
          - href: labs/lab1/assignment1_template.qmd
            text: Assignment 1
          - href: labs/lab2/Rigsby_Joshua_Assignment2.qmd
            text: Assignment 2
          - href: labs/lab3_midterm/Midterm_2025_Slides.qmd
            text: Midterm Slides
          - href: labs/lab3_midterm/Midterm_2025_Technical_Appendix.qmd
            text: Midterm Technical Appendix
          - href: labs/lab4/Actual Assignment 4 copy.qmd
            text: Assignmnet 4
          - href: labs/lab5/Indego_SpaceTime_Prediction_Q2.Rmd
            text: Assignmnet 5
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
